#ifndef EDITORAUTOBUILD_GLOBAL_H
#define EDITORAUTOBUILD_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef EDITORAUTOBUILD_LIB
# define EDITORAUTOBUILD_EXPORT Q_DECL_EXPORT
#else
# define EDITORAUTOBUILD_EXPORT Q_DECL_IMPORT
#endif

#endif // EDITORAUTOBUILD_GLOBAL_H
