#ifndef EDITORGUICOMMON_GLOBAL_H
#define EDITORGUICOMMON_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef EDITORGUICOMMON_LIB
# define EDITORGUICOMMON_EXPORT Q_DECL_EXPORT
#else
# define EDITORGUICOMMON_EXPORT Q_DECL_IMPORT
#endif

#endif // EDITORGUICOMMON_GLOBAL_H
